name: Node.js CI

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_FIREBASE_SERVICE_ACCOUNT_BASE64: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }}
          envkey_MIXPANEL_PROJECT_TOKEN: ${{ secrets.MIXPANEL_PROJECT_TOKEN }}
          envkey_PAYSTACK_BASEURL: ${{ secrets.PAYSTACK_BASEURL }}
          envkey_PAYSTACK_SECRET_KEY: ${{ secrets.PAYSTACK_SECRET_KEY }}
          directory: ./
          file_name: .env
          fail_on_empty: false
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: make test
