name: Node.js CI

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
      runs-on: ubuntu-latest
      services:
        mysql:
          image: mysql:5.7
          env:
            MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASS }}
            MYSQL_USER: ${{ secrets.DB_USER }}
            MYSQL_DATABASE: ${{ secrets.DB_NAME }}
    
      steps:
      - uses: actions/checkout@v3
      - uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_FIREBASE_SERVICE_ACCOUNT_BASE64: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }}
          envkey_MIXPANEL_PROJECT_TOKEN: ${{ secrets.MIXPANEL_PROJECT_TOKEN }}
          envkey_PAYSTACK_BASEURL: ${{ secrets.PAYSTACK_BASEURL }}
          envkey_PAYSTACK_SECRET_KEY: ${{ secrets.PAYSTACK_SECRET_KEY }}
          envkey_DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          envkey_DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          envkey_DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          envkey_DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          envkey_DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
          directory: ./
          file_name: .env
          fail_on_empty: false
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: make test
